language: csharp
solution: KWADTool.sln

addons:
  apt:
    packages:
    - p7zip-full

script:
- xbuild /p:Configuration=Release KWADTool.sln

env:
- BUILD_OUTPUT_DIR="KWADTool/bin/Release" ARTIFACT_NAME="KWADTool-${TRAVIS_TAG}.zip"

before_deploy: 
- cd ${BUILD_OUTPUT_DIR}
- 7z a ${ARTIFACT_NAME} *.dll KWADTool.exe KWADTool.exe.config
- cd -
deploy:
  provider: releases
  api_key:
    secure: o1DhzwMHIFyyWPtaCAUb8TceOz0STooQ9fFqqWphBiDHhoLWP9M5p1dXsS7byGVvfUDspWN4357gDpyThV2nQgnjlpGd7Scf8LmmFwv5U7We5LTVYnnllQJ12lkfg1hLpAUYNgCdZ97jJ8cr555yf6HKe/Wb/W+SYe7HbmRBwBzkp8xTsnje6iiMjctJ0IY5N2yyVf7R9B/0hWgUbK5S4waFJ7BtVHj4dZlim8agf7Fw55i7rdVq0b1H4tCfS3EdyLYhFCQulMAXLmgX175qxQv4Ob5izfz1Op89f+2wSpVTJBUEr50zSUgqXZDPx2S0KnoO9jZisguWp01FaNEsXSBsqVhOvaQemayMlmtXdwfWCtUc/s9pqFKDjI/UAGW5MrWrWTBp45XyvxEBPGW5OY2Q5RjzbEYQSS1259VwtstvYZL397J/+ny3MEIiEWXV1gTyCs98tkU7PKhakkb6JmhSFhRjJQxkLxgVpmNdL9uMH3HEelFC8qUPSJOt3NQnnD0UN3Z6uDAs+rj4vVjIRyncrClezi1WNEihLghEF3kJJVfMg80ougWWlkLNCCdcONc5NS6mdKRs9kMu33LdUUszZIt2uYBPMRLdv2ZaUzXGWTvp5D9RFE/Bt37z6LHHYRLbFQCzT85hxf0V7d/sTU+RFEZbRSK8FMIvd92i2bQ=
  file: ${BUILD_OUTPUT_DIR}/${ARTIFACT_NAME}
  skip_cleanup: true
  on:
    tags: true
